version: '2'

services:
    mariadb:
        image: 'bitnami/mariadb:latest'
        environment:
            - MARIADB_USER=bn_testlink
            - MARIADB_DATABASE=bitnami_testlink
            - ALLOW_EMPTY_PASSWORD=yes
        volumes:
            - 'mariadb_data:/bitnami'
    testlink:
        image: 'bitnami/testlink:latest'
        environment:
            - TESTLINK_USERNAME=admin
            - TESTLINK_PASSWORD=password
            - TESTLINK_EMAIL=admin@example.com
            - TESTLINK_LANGUAGE=en_US
            - MARIADB_HOST=mariadb
            - MARIADB_PORT_NUMBER=3306
            - TESTLINK_DATABASE_NAME=bitnami_testlink
            - TESTLINK_DATABASE_USER=bn_testlink
            - ALLOW_EMPTY_PASSWORD=yes
            - SMTP_ENABLE=true
            - SMTP_HOST=smtp.gmail.com
            - SMTP_PORT=587
            - SMTP_USER=pruebaplanoalcanos@gmail.com
            - SMTP_PASSWORD=carlos1A
            - SMTP_CONNECTION_MODE=tls
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - 'testlink_data:/bitnami'
        depends_on:
            - mariadb

volumes:
    mariadb_data:
        driver: local
    testlink_data:
        driver: local

